localgov_publications_importer.import_pipeline.*:
  type: config_entity
  label: 'Import Pipeline'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    extract_plugin:
      type: string
      label: 'Extract Plugin'
    extract_plugin_configuration:
      type: ignore
      label: 'Extract Plugin Configuration'
    transform_plugins:
      type: sequence
      label: 'Transform Plugins'
      sequence:
        type: ignore
    transform_plugin_configurations:
      type: ignore
      label: 'Transform Plugin Configurations'
    save_plugin:
      type: string
      label: 'Save Plugin'
    save_plugin_configuration:
      type: ignore
      label: 'Save Plugin Configuration'
